# Generated by Django 3.2.9 on 2024-01-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleveryAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_with_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.FloatField(blank=True, default=0, null=True)),
                ('due_amount', models.FloatField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('order_sheet', models.CharField(blank=True, default='order', max_length=100, null=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(blank=True, default='incomplete', max_length=100, null=True)),
                ('invoice_by', models.CharField(max_length=100)),
                ('systemname', models.CharField(blank=True, max_length=100, null=True)),
                ('your_datetime_field', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErpApp.customerlist')),
                ('pos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErpApp.setpos')),
                ('products', models.ManyToManyField(to='ErpApp.InvoiceProduct')),
            ],
        ),
    ]
