# Generated by Django 4.2.7 on 2023-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0002_invoiceproduct_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Print_As', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Fax', models.CharField(blank=True, max_length=50, null=True)),
                ('Website', models.CharField(blank=True, max_length=50, null=True)),
                ('Contact_Person', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.TextField(null=True)),
                ('Thana', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Status', models.BooleanField(blank=True, null=True)),
                ('Branch', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
