# Generated by Django 3.2.9 on 2024-01-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0002_deleveryadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='setposcancelation',
            name='posid_show',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='ErpApp.setpos'),
        ),
    ]
