# Generated by Django 3.2.9 on 2024-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0003_setposcancelation_posid_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleveryadd',
            name='serial_name',
            field=models.CharField(default='SD', max_length=100),
        ),
        migrations.AddField(
            model_name='setpos',
            name='serial_name',
            field=models.CharField(default='SO', max_length=100),
        ),
        migrations.AddField(
            model_name='setposcancelation',
            name='serial_name',
            field=models.CharField(default='SO/CL', max_length=100),
        ),
        migrations.AddField(
            model_name='setpospurchase',
            name='serial_name',
            field=models.CharField(default='PO', max_length=100),
        ),
    ]
