# Generated by Django 4.2.7 on 2023-12-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0003_partylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPosPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_with_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_by', models.CharField(max_length=100)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErpApp.partylist')),
                ('products', models.ManyToManyField(to='ErpApp.invoiceproduct')),
            ],
        ),
    ]
