# Generated by Django 3.2.9 on 2024-01-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0004_auto_20240111_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpos',
            name='description',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
