# Generated by Django 3.2.9 on 2024-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0005_setpos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleveryadd',
            name='description',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
