# Generated by Django 4.2.7 on 2023-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0005_setpospurchase_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpospurchase',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='setpospurchase',
            name='due_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='setpospurchase',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
