# Generated by Django 4.2.7 on 2023-12-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0006_setpospurchase_amount_setpospurchase_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpospurchase',
            name='approved_by',
            field=models.CharField(blank=True, default='Hussain', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setpospurchase',
            name='branch',
            field=models.CharField(blank=True, default='Head Branch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setpospurchase',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Start Progress', 'Start Progress'), ('Complete', 'Complete'), ('Reject', 'Reject'), ('Close', 'Close')], default='pending', max_length=100, null=True),
        ),
    ]
