# Generated by Django 4.2.7 on 2023-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0007_setpospurchase_approved_by_setpospurchase_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
