# Generated by Django 4.2.7 on 2023-12-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0008_alter_invoiceproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='setpospurchase',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Start Progress', 'Start Progress'), ('Complete', 'Complete'), ('Reject', 'Reject'), ('Close', 'Close')], default='Pending', max_length=100, null=True),
        ),
    ]
