# Generated by Django 3.2.9 on 2024-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0008_auto_20240116_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='po_number',
            field=models.CharField(blank=True, default='PO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='so_number',
            field=models.CharField(blank=True, default='SO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setpos',
            name='delivery_status',
            field=models.CharField(blank=True, default='incomplete', max_length=100, null=True),
        ),
    ]
