# Generated by Django 4.2.7 on 2023-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0009_product_max_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('national_id', models.CharField(max_length=255)),
                ('hired_date', models.DateField()),
                ('card_number', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('termination_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
