# Generated by Django 4.2.7 on 2023-12-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpos',
            name='delivery_status',
            field=models.CharField(blank=True, default='incomplete', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setpos',
            name='due_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='setpos',
            name='order_sheet',
            field=models.CharField(blank=True, default='order', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setpos',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
