# Generated by Django 4.2.7 on 2023-12-24 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0011_setpos_delivery_status_setpos_due_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info_status', models.CharField(blank=True, choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], default='Cash', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='setpos',
            name='systemname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vouchernumber', models.IntegerField(default=0)),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('Bank Deposit', 'Bank Deposit'), ('Card', 'Card'), ('Bkash', 'Bkash')], default='Cash', max_length=100, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErpApp.paymentmethodname')),
                ('purchasepos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ErpApp.setpospurchase')),
                ('salepos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ErpApp.setpos')),
            ],
        ),
    ]
